baseurl = "https://isandu.github.io/website/"
publishDir = "docs"
relativeurls = true
languageCode = "en-us"
title = "A Hugo website"
theme = "slim"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$", "^Thumbs\\.db$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"

[params]
  AnalyticsID = "UA-97660311-1"
  DisqusShortname = "isandu-1"
  Summary = false  # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
  # FooterMsg = "Copyright Me 2016. Powered by Hugo."

