disqusShortname = "isandu-1"
baseurl = "https://isandu.github.io/website/"
publishDir = "docs"
relativeurls = true
languageCode = "en-us"
title = "Accounting"
theme = "slim"
googleAnalytics = "UA-97660311-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$", "^Thumbs\\.db$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"

[params]
    description = "A website with accounting exercises."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"